title: John Doe # your name (or website title) here
logo: "/images/nslogo1.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Quam nulla porttitor massa id neque aliquam vestibulum. Egestas sed sed risus pretium quam vulputate dignissim. Amet nulla facilisi morbi tempus iaculis urna id volutpat. Amet consectetur adipiscing elit pellentesque habitant morbi tristique senectus.
  <br><br>
  Nunc consequat interdum varius sit amet mattis vulputate enim. Urna neque viverra justo nec ultrices dui sapien eget. Viverra aliquet eget sit amet tellus cras. Pulvinar elementum integer enim neque. Eu ultrices vitae auctor eu augue.
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
